In [1]:
import numpy as np # importar numpy

In [8]:
# Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz 
# en la que cada elemento es una suma de elementos de las 2 matrices?

matriz1 = np.array([[9, 8, 7], [1, 2, 3], [6, 5, 4]]) # crear matriz 1
matriz2 = np.array([[3, 2, 1], [4, 5, 6], [7, 8, 9]]) # crear matriz 2

matriz3 = matriz1 + matriz2 # realizar la suma de ambas matrices
print(matriz3) # Imprimir la matriz resultante

[[12 10  8]
 [ 5  7  9]
 [13 13 13]]


In [3]:
# Cree una matriz de identidad de dimensión 4

matriz_identidad = np.identity(4) # crear matriz de 4 dimensiones

print(matriz_identidad) # Imprimir la matriz identidad

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana.

matriz_binaria = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 0]])  # crear una matriz binaria
matriz_booleana = matriz_binaria.astype(bool)  # convertir la matriz binaria en una matriz booleana
print(matriz_booleana)  # Imprimir la matriz booleana resultante

[[ True False  True]
 [False  True False]
 [ True False False]]


In [14]:
# Genere una secuencia de números en forma de matriz numpy de 0 a 100 
# con espacios de 2 números, por ejemplo: 0, 2, 4 ...

matriz_4 = np.arange(0,101,2) # crear matriz con la secuencia de números de 0 a 100 con espacios de 2 números
matriz_4   # Imprimir la matriz

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])